### ISSUE TITLE
Total invested amount is wrong

### ISSUE THREAD

**Issue by 1nusah** [nanaaikinson/loan-management#13]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/38425952/229151088-e17e0616-889c-42a2-90ac-7209ded3db2a.png">

I created two loans. First loan was rejected and the amount was 15k, second loan was approved and the amount was 10k. The total invested amount shouldn't rejected loans but it shows a total of 25k

**Comment by nanaaikinson** [comment]
Fix from API repo with commit [https://github.com/nanaaikinson/microlend-api/commit/8217817f144e6942109609dee7c40f73a7cf7237](https://github.com/nanaaikinson/microlend-api/commit/8217817f144e6942109609dee7c40f73a7cf7237)
